Added unit test for Webserver.cc
UCLA-CS130/Team-KBBQ pull request #3
Opened 2017-01-25 05:07 UTC by tyhchoi

Did not test this yet

2017-01-25 05:20 UTC, llam15 requested changes

2017-01-25 05:20 UTC, llam15 commented on Webserver_test.cc
> +#include "webserver.cc"
#include "Webserver.h"

2017-01-25 05:20 UTC, llam15 commented on Webserver_test.cc
> +	  tcp::resolver resolver (io_service);
You might need to use the namespace boost::asio::ip::tcp

2017-01-25 05:20 UTC, llam15 commented on Webserver_test.cc
> +    tcp::resolver::iterator endpoint_iterator = resolver.resolve(query);
What's happening with the indents lmao

2017-01-25 05:20 UTC, llam15 commented on Webserver_test.cc
> +	  tcp::resolver::query query(localhost:8080, "asdf");
tcp::resolver::query query(tcp::v4(), localhost, 8080);

2017-01-25 05:20 UTC, llam15 commented on Webserver_test.cc
> +	  server.run_server(io_service, 8080);
We changed the implementation of run_server. You will need to run server.parse_config(config_file) then server.run_server(io_service)

2017-01-25 05:20 UTC, llam15 commented on Webserver_test.cc
> +    boost::asio::write(socket, request);
I think you have to pass in request.data()?

2017-01-26 07:38 UTC, tyhchoi commented on Webserver_test.cc
> +	  tcp::resolver::query query(localhost:8080, "asdf");
i found out its supposed to be query("localhost", "8080");

2017-01-26 07:43 UTC, tyhchoi commented on Webserver_test.cc
> +    boost::asio::write(socket, request);
i think the first argument is the socket and the next is the buffer

2017-02-06 06:37 UTC, closed without merging